<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="helloworld_tests.HelloWorldTest-20221106205022" tests="5" file="helloworld_tests.py" time="0.021" timestamp="2022-11-06T20:50:23" failures="2" errors="0" skipped="0">
	<testcase classname="helloworld_tests.HelloWorldTest" name="test_isupper" time="0.001" timestamp="2022-11-06T20:50:23"/>
	<testcase classname="helloworld_tests.HelloWorldTest" name="test_should_issue_hello_world_message" time="0.001" timestamp="2022-11-06T20:50:23"/>
	<testcase classname="helloworld_tests.HelloWorldTest" name="test_split" time="0.001" timestamp="2022-11-06T20:50:23"/>
	<testcase classname="helloworld_tests.HelloWorldTest" name="test2" time="0.014" timestamp="2022-11-06T20:50:23">
		<failure type="VerificationError" message="
Wanted but not invoked:

    write('Hello world of Monty Python\n')

Instead got:

    write('Hello world of Python\n')

"><![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/media/Datacenter/google/education/torrens/DOT/DOT/src/unittest/python/helloworld_tests.py", line 15, in test2
    verify(out).write("Hello world of Monty Python\n")
  File "/usr/lib/python3/dist-packages/mockito/invocation.py", line 242, in __call__
    self.verification.verify(self, len(matched_invocations))
  File "/usr/lib/python3/dist-packages/mockito/verification.py", line 93, in verify
    raise VerificationError(
mockito.verification.VerificationError: 
Wanted but not invoked:

    write('Hello world of Monty Python\n')

Instead got:

    write('Hello world of Python\n')


]]></failure>
	</testcase>
	<testcase classname="helloworld_tests.HelloWorldTest" name="test_upper" time="0.004" timestamp="2022-11-06T20:50:23">
		<failure type="AssertionError" message="'FOO' != 'FOo'
- FOO
?   ^
+ FOo
?   ^
"><![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.10/unittest/case.py", line 591, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.10/unittest/case.py", line 549, in _callTestMethod
    method()
  File "/media/Datacenter/google/education/torrens/DOT/DOT/src/unittest/python/helloworld_tests.py", line 18, in test_upper
    self.assertEqual('foo'.upper(), 'FOo')
  File "/usr/lib/python3.10/unittest/case.py", line 845, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.10/unittest/case.py", line 1226, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/usr/lib/python3.10/unittest/case.py", line 675, in fail
    raise self.failureException(msg)
AssertionError: 'FOO' != 'FOo'
- FOO
?   ^
+ FOo
?   ^

]]></failure>
	</testcase>
</testsuite>
